name: Tourism Pipeline (HF Scripts)

on:
  push:
    branches:
      - main

jobs:

  pipeline:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3


      # 2. Install dependencies
      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn joblib datasets huggingface_hub


      # 3. Download dataset
      - name: Download Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scripts/download_dataset.py


      # 4. Download model
      - name: Download Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python scripts/download_model.py


      # 5. Debug (VERY IMPORTANT)
      - name: Verify Files
        run: |
          echo "📂 Files:"
          ls -R


      # 6. Test model
      - name: Run Model Test
        run: |
          python scripts/test_model.py
